"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var prompt_sync_1 = require("prompt-sync");
var prompt = (0, prompt_sync_1.default)();
console.log("me diga os nomes das pessoas");
var nome1 = prompt("nome: ");
var nome2 = prompt("nome: ");
console.log("me diga a idade das pessoas");
var idade1 = Number(prompt("idade: "));
var idade2 = Number(prompt("idade: "));
var media = (idade1 + idade2) / 2;
console.log("a idade media de ".concat(nome1, " e ").concat(nome2, " \u00E9 de ").concat(media.toFixed(1), " anos"));
